### PR TITLE
One more fix for relay_port and MQTT addon host

### PR DESCRIPTION
**Pull request by andriej**
One file was missing relay_port edit.
Added HA's default MQTT broker address and to make it more popular, suggestion of possibility to use not only MQTT but OT integration too.

### CODE REVIEW

**Comment by andriej** [comment]
@basnijholt maybe it's worth to start versioning addon, for easy updates in Supervisor?

**Comment by basnijholt** [comment]
I’m ahead of you https://github.com/basnijholt/addon-otmonitor/releases

**Comment by andriej** [comment]
I'm not sure if it's sufficient or something more should be done, as it's not proposing update on my supervisor yet.
I've reloaded repos :-)
image

**Comment by basnijholt** [comment]
You are right, I need to change this line
https://github.com/basnijholt/addon-otmonitor/blob/13d805186060372b39e249653faee577692319f6/otmonitor/config.json#L3

**Pull request merged**
