### PR TITLE
Added otmonitor ports to addon config

### PR DESCRIPTION
**Pull request by iamkarlson**

### CODE REVIEW

**Comment by basnijholt** [comment]
That's great! Did you test it and it works?

**Comment by iamkarlson** [comment]
Yes, I've tested this from my [repo](https://github.com/iamkarlson/addon-otmonitor/), it works. Nonetheless, it's being very slow as an addon in general and I can't understand why, is it because of the settings for ports, or something else is breaking the stuff. Why I'm adding is that because the original addon doesn't seem to be working in my setup. I'm trying to investigate further.

**Comment by basnijholt** [comment]
Hmm, that is strange, for me, it's a very fast add-on...

What do you mean with "original add-on"? Do you mean this repo?

**Comment by iamkarlson** [comment]
yes, your repo

**Comment by iamkarlson** [comment]
Reverted back to your repo - addon is still very slow

**Comment by basnijholt** [comment]
So it the code of this PR still useful? Because it didn't solve your problem AFAIU.

**Comment by iamkarlson** [comment]
It depends on your setup. if you want to have access to otmonitor without home assistant - you need these settings. otherwise you don't. this is a kind of personal preferences, so please decide what would you want to have exposed in this addon

**Pull request merged**
